### ISSUE TITLE
Some game crash and graphics problem I have recently

### ISSUE THREAD

**Issue by NeoAstray** [Flemmli97/FateUBW#1]
#### Issue (The better the description the better i can solve the issue):
<img width="592" alt="Screen Shot 2019-05-14 at 6 14 14 PM" src="https://user-images.githubusercontent.com/50641100/57735899-1dd08700-7674-11e9-8011-72568ebef20b.png">
The game crash when i try to launch it on 1.12.2 14.23.5.2768 forge when only this mod with the library is loaded. 
I'm able to open the game with other mods on 1.12.2 14.23.5.2768 forge but everything looks like this
<img width="1440" alt="Screen Shot 2019-05-14 at 6 18 33 PM" src="https://user-images.githubusercontent.com/50641100/57736098-cb439a80-7674-11e9-8996-d99e02efdbbd.png">
<img width="1440" alt="Screen Shot 2019-05-14 at 6 19 47 PM" src="https://user-images.githubusercontent.com/50641100/57736125-e0202e00-7674-11e9-9380-31df2429777e.png">

#### Steps to reproduce:
Open the game alone with 1.12.2 14.23.5.2768 forge and then the game crash

or

Open the game with these mods and everything turns into white blocks like the picture above
<img width="1237" alt="Screen Shot 2019-05-14 at 6 21 11 PM" src="https://user-images.githubusercontent.com/50641100/57736201-22496f80-7675-11e9-9bc2-99335faa8e5a.png">

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.12.2
- Forge: 1.12.2 14.23.5.2768
- TenshiLib: 1.12.2 1.1.1
- Fate/UBW:1.12.2 a0.3.0

#### Other Mods (If you think it might be cause of an incompability):

<img width="1237" alt="Screen Shot 2019-05-14 at 6 21 11 PM" src="https://user-images.githubusercontent.com/50641100/57736260-545ad180-7675-11e9-94c9-6ca5ff14cc88.png">

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):  
[B2EbnMN9.txt](https://github.com/Flemmli97/FateUBW/files/3180118/B2EbnMN9.txt)

Thanks for helping out! It is a mod with great ideas!

**Comment by Flemmli97** [comment]
can you try a newer forge version and see if this issue still persist?

**Comment by Flemmli97** [comment]
closed since no reply. reopen if the issue still persist
